### ISSUE TITLE
Inventory -- Does not save selected currency

### ISSUE THREAD

**Issue by mkaito** [mkaito/VikingReborn#12]

**Comment by mkaito** [comment]
@Zeirk didn't you make a whole new inventory window?

**Comment by Zeirk** [comment]
Yes I did.

**Comment by mkaito** [comment]
Does that look merge-worthy?

**Comment by Zeirk** [comment]
Should be, I wouldn't see why not I tested most the stuff, it's all working afaik.

**Comment by Zeirk** [comment]
K, lets hope this works lol.

**Comment by mkaito** [comment]
It did work, but can you please try to put it all into one PR? :stuck_out_tongue:

**Comment by Zeirk** [comment]
Yea I'll try to figure that out lol sorry.
