### ISSUE TITLE
Focus Bar Tooltips

### ISSUE THREAD

**Issue by mgasparel** [mkaito/VikingReborn#17]
Focus bar tooltips are showing castbar progress instead of focus

**Comment by mkaito** [comment]
Could you provide a screenshot?

**Comment by mkaito** [comment]
![focustooltip1](https://cloud.githubusercontent.com/assets/20434/10544271/58d82aca-741a-11e5-8192-f8373eebfdc2.png)
![focustooltip2](https://cloud.githubusercontent.com/assets/20434/10544272/58d87994-741a-11e5-91a7-ad6abef09416.png)

**Comment by Zeirk** [comment]
I have a fix for this, it seems degen commented out a lot of the tooltip stuff for this.
