### ISSUE TITLE
Inventory Options close when clicking in inventory.

### ISSUE THREAD

**Issue by mkaito** [mkaito/VikingReborn#32]
... making it hard to equip new bags. You can, however, click to pick up the bag from inventory, then click options button, and then put bag into slot. That's counter intuitive, however.

**Comment by Zeirk** [comment]
The OptionsContainer has CloseOnExternalClick enabled, which is default I might add, never thought to look into that.

**Comment by mkaito** [comment]
Fixed that. Will push when I get push access again.
