### ISSUE TITLE
UnitFrames error

### ISSUE THREAD

**Issue by synonymouse** [mkaito/VikingReborn#37]
...ildStar\Addons\VikingUnitFrames\VikingUnitFrames.lua:267: attempt to call global 'SendVarToRover' (a nil value)
stack trace:
    ...ildStar\Addons\VikingUnitFrames\VikingUnitFrames.lua:267: in function <...ildStar\Addons\VikingUnitFrames\VikingUnitFrames.lua:261>

**Comment by mkaito** [comment]
Hi!

Thanks for reporting. Issue #36 is already fixed. Could you please download the latest version and confirm?

**Comment by synonymouse** [comment]
i did. This new error after a fix

**Comment by mkaito** [comment]
Man, I really need my coffee.
