### ISSUE TITLE
Project and org name

### ISSUE THREAD

**Issue by mkaito** [mkaito/VikingReborn#48]
I didn't actually get much feedback on this in gitter, so here it is for a broader discussion.

I called it VikingReborn on a whim, taking inspiration from EQ2's ProfitUI which was abandoned and picked up and renamed Profit Reborn.

I think Vikings are awesome, but I feel like the Reborn part doesn't really speak to me after all.

So what other ideas do we have?

My own:
- Ask @itsthatguy for permission to use the vikinghug organization, assuming at least 3 of us get full access as gatekeepers, and just keep everything there, rename it back to VikingUI.
- Some kind of play on Valhalla and the Einherjar, based on Norse mythology concerning the afterlife of vikings.
- A completely different name for both the organization and the project.

**Comment by itsthatguy** [comment]
@mkaito do you want to be an admin of the vikinghug org?

**Comment by itsthatguy** [comment]
I'd recommend just keeping the brand name the same, if you want to benefit from it's already established popularity.

**Comment by mkaito** [comment]
@itsthatguy I think that'd be a good idea. If you make me an admin, I'll move everything there and take care of it. I was just wary of intruding on a group of friends or something like that.

**Comment by itsthatguy** [comment]
@mkaito, you should join the IRC channel on Freenode: #vikinghug

**Comment by itsthatguy** [comment]
Never! It's open source for a reason! The more love the better!

**Comment by mkaito** [comment]
Then that's settled. I'll pop in #vikinghug when I get home from work. Thanks!
